# Generated by Django 2.1.4 on 2019-01-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driverUserId',
            new_name='driverName',
        ),
    ]
