# Generated by Django 2.1.4 on 2019-01-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190124_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='approvalUserId',
            field=models.CharField(max_length=20, null=True, verbose_name='审核人员'),
        ),
    ]
