# Generated by Django 2.1.4 on 2019-01-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190125_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='approvalUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', to_field='userId', verbose_name='审核人员'),
        ),
    ]
