# Generated by Django 2.1.4 on 2019-01-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190125_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='otherFee',
            field=models.CharField(max_length=255, null=True, verbose_name='其它费用附件'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
