# Generated by Django 2.1.4 on 2019-01-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190125_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='useTime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='使用时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='persona',
            field=models.SmallIntegerField(choices=[(0, '普通用户'), (1, '管理员'), (2, '审核员'), (3, '派车员'), (4, '司机')], default=0),
        ),
    ]
