# Generated by Django 2.1.4 on 2019-01-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190129_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
